---
title: "Lab Resources"
date: '`r format(Sys.time(), "%d %B, %Y")`'
---

```{r setup, include = F}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(knitr)
  knitr::opts_chunk$set(echo = F)
  knitr::opts_chunk$set(warning = F)
  knitr::opts_chunk$set(message = F)
```


---


#### **Forms** 

[University of Arkansas GSIE](https://graduate-students.uark.edu/)

[Campus Map with Lactation Rooms and Accessible Points](https://campusmaps.uark.edu/?pnl_disp=N&accessible_pt=Y&id=2110#!ct/94027,94028,94029,94030) 

[Anthony Travel](https://travel.uark.edu/travel-arrangements/anthony-travel-agency.php)

[International Travel & Export Control](https://travel.uark.edu/travel-policy/international-travel.php)

[Travel Survival Guide](https://uark.sharepoint.com/sites/wdt/SitePages/Travel-Survival-Guide.aspx)


---


#### **Lab Reading List**

Reading and synthesizing information is essential to succed in graduate school. Below is the recommended reading list to start developing common knowledge base as a productive lab group member.  


---

#### **Statistics and Experimental Design**

**Books** 

* Staton, Ben. Introduction to R for Natural Resource Scientists. n.d. [Accessed January 30, 2026.](https://bstaton1.github.io/au-r-workshop/index.html#prerequisites.)

* Hacking, I. (2006) The emergence of probability: A philosophical study of early ideas about probability, induction and statistical inference. [Cambridge University Press. 2006](https://www.cambridge.org/core/books/emergence-of-probability/9852017A380C63DA30886D25B80336A7)

* Hilborn, R. and Mangel, R. (1997) The Ecological Detectives. [Princeton University Press. March 6, 1997.](https://press.princeton.edu/books/paperback/9780691034973/the-ecological-detective?srsltid=AfmBOoq-IauLl5_2ori5E6piclVPT_LnMVc8fiRmGeZPEjTXt51XbDSi)

* Isaaks, E.H. and Srivastava R.M. (1989) An Introduction to Applied Geostatistics. [Oxford University Press, 1989.](https://www.amazon.com/Introduction-Applied-Geostatistics-Edward-Isaaks/dp/0195050134)


---


**Papers**

* Hurlbert, S. H. Pseudoreplication and the design of ecological field experiments. [Ecol. Monogr. 54, 187–211 (1984).](https://esajournals.onlinelibrary.wiley.com/doi/10.2307/1942661)

* Allen, C. R., D. G. Angeler, G. S. Cumming, C. Folke, D. Twidwell, and D. R. Uden. 2016. Quantifying spatial resilience. [Journal of Applied Ecology 53:625–635.](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.12634)


---


#### **Ecology**

* Courchamp, Franck, and Corey J. A. Bradshaw. 100 Articles Every Ecologist Should Read. [Nature Ecology & Evolution 2, no. 2 (2018): 395–401. https://doi.org/10.1038/s41559-017-0370-9.](https://d0050464-881e-4bab-900f-557585398015.filesusr.com/ugd/9b6d5d_31ab1ea20ed247e7a4ce788506304070.pdf)

**And some more:** 

* Real, Leslie A., and James H. Brown, eds. Foundations of Ecology: Classic Papers with Commentaries. [University of Chicago Press, 1991.](https://press.uchicago.edu/ucp/books/book/chicago/F/bo3613618.html)

* Wiens, John A., Michael R. Moss, Monica G. Turner, and David Mladenoff, eds. Foundation Papers in Landscape Ecology. [Columbia University Press, 2006.](https://cup.columbia.edu/book/foundation-papers-in-landscape-ecology/9780231126809/)


---


>These materials are not endorsed, approved, sponsored, or provided by or on behalf of the University of Arkansas, Fayetteville.


---
